### ISSUE TITLE
The "data" option should be a function error after minimal installation of speedkit

### ISSUE THREAD

**Issue by bhaskar-nair2** [GrabarzUndPartner/nuxt-speedkit#258]
**Describe the bug**
`The "data" option should be a function that returns a per-instance value in component definitions` Error thrown in dev mode after minimal installation.

**To Reproduce**
1. `npm i nuxt-speedkit`
2. add `nuxt-speedkit` to modules
3. Run dev server with `npm run dev`
4. The error is thrown in the console

**Screenshots**
Line 8 from bottom shows error is somehow linked to speedkit.
![image](https://user-images.githubusercontent.com/18023085/113019965-c2440f80-919f-11eb-90b0-6bb781d2456f.png)

**Versions**
 - nuxt-speedkit: 1.1.27
 - Nuxt: 2.15.3
 - Browser: Chrome 88.0.4324.182

**Additional context**
https://www.reddit.com/r/Nuxt/comments/mfqthj/nuxtspeedkit_will_help_you_to_improve_the/gst3yzb?utm_source=share&utm_medium=web2x&context=3

**Comment by bhaskar-nair2** [comment]
Also, removing `nuxt-speedkit` removes this error

**Comment by ThornWalli** [comment]
Hi bhaskar-nair2,

here is a simple sandbox (https://codesandbox.io/s/nervous-rosalind-1lni4) with the integration.

It's a bit difficult to see where the error is coming from.
The background of the stacktrace is that the app entry is replaced by its own, therefore `nuxt-speedkit` appears in the stacktrace. 

This is important for the controlled initialisation, [more information](https://nuxt-speedkit.grabarzundpartner.dev/components/speedkit-layer#solution).

**Comment by bhaskar-nair2** [comment]
Given my project's code base right now is too huge to go and analyze where this specific error is coming from I'd just say it's an issue on my end and close this.

**Comment by justinmetros** [comment]
Got the same issue on minimal install. Commented out all my components and it was still there. Will try to get a repro if I can find the time tomorrow.
