### ISSUE TITLE
FontConfig is failed

### ISSUE THREAD

**Issue by gerasimovs** [GrabarzUndPartner/nuxt-speedkit#268]
When you run the  `npm run build` command, a warning is displayed: ` TypeError: Array.from(...).map(...).flat(...) is not a function or its return value is not iterable`

at FontConfig.toCSS (node_modules/nuxt-speedkit/classes/FontConfig.js:20:10)

nuxt.config.js:

```
speedkit: {
    detection: {
      performance: true,
      browserSupport: true,
    },
    performance: {
      device: {
        hardwareConcurrency: { min: 2, max: 48 },
        deviceMemory: { min: 2 },
      },
      timing: {
        fcp: 400,
        dcl: 800,
      },
      lighthouseDetectionByUserAgent: false,
    },
    fonts: [{
      family: 'RobotoCondensed Regular',
      locals: ['RobotoCondensed Regular'],
      fallback: ['sans-serif'],
      variances: [{
        style: 'normal',
        weight: 400,
        sources: [
          { src: '~assets/fonts/RobotoCondensed-Regular.woff2?v=1.0', type: 'woff2' },
          { src: '~assets/fonts/RobotoCondensed-Regular.woff?v=1.0', type: 'woff' },
          { src: '~assets/fonts/RobotoCondensed-Regular.ttf?v=1.0', type: 'truetype' },
          { src: '~assets/fonts/RobotoCondensed-Regular.svg#Formular-Black?v=1.0', type: 'svg' },
          { src: '~assets/fonts/RobotoCondensed-Regular.eot?#iefix?v=1.0', type: 'embedded-opentype' },
        ],
      }],
    }],

    componentAutoImport: false,
    componentPrefix: undefined,

    /**
     * IntersectionObserver rootMargin for Compoennts and Assets
     */
    lazyOffset: {
      component: '0%',
      asset: '0%',
    },
  },
```

**Comment by ThornWalli** [comment]
Hi gerasimovs,

Your source definition is a bit invalid :)

Try it with

```js
  sources: [
    { src: '~assets/fonts/RobotoCondensed-Regular.woff2', type: 'woff2' },
    { src: '~assets/fonts/RobotoCondensed-Regular.woff', type: 'woff' }
  ],
```

You don't need `eot`, `ttf` or `svg` as font, all modern browsers can all do `woff2` except `IE 11` with `woff`.

https://caniuse.com/?search=woff2
https://caniuse.com/?search=woff

Problem with your definition is the `?` parameters and `#` for the `svg`, the sources are resolved via the alias `~` per require, no parameter passing would be possible there.

**Comment by gerasimovs** [comment]
In fact, even if the array is empty `fonts`, then the error does not disappear.

`fonts: [],`

> Try it with
> 
> ```js
>   sources: [
>     { src: '~assets/fonts/RobotoCondensed-Regular.woff2', type: 'woff2' },
>     { src: '~assets/fonts/RobotoCondensed-Regular.woff', type: 'woff' }
>   ],
> ```
> 
> You don't need `eot`, `ttf` or `svg` as font, all modern browsers can all do `woff2` except `IE 11` with `woff`.
> 
> https://caniuse.com/?search=woff2
> https://caniuse.com/?search=woff
> 
> Problem with your definition is the `?` parameters and `#` for the `svg`, the sources are resolved via the alias `~` per require, no parameter passing would be possible there.

Your option doesn't work either. There is a suspicion of the flat-function (by https://stackoverflow.com/questions/50993498/flat-is-not-a-function-whats-wrong)

```
fonts: [{
      family: 'RobotoCondensed Regular',
      locals: ['RobotoCondensed Regular'],
      fallback: ['sans-serif'],
      variances: [{
        style: 'normal',
        weight: 400,
        sources: [
          { src: '@/assets/fonts/RobotoCondensed-Regular.woff2', type: 'woff2' },
          { src: '@/assets/fonts/RobotoCondensed-Regular.woff', type: 'woff' },
        ],
      }],
    }],
```


```
 FATAL  Array.from(...).map(...).flat(...) is not a function or its return value is not iterable                                                                                                                     20:19:06

  at FontConfig.toCSS (node_modules/nuxt-speedkit/classes/FontConfig.js:20:10)
  at addBuildTemplates (node_modules/nuxt-speedkit/module.js:72:36)
  at ModuleContainer.module.exports (node_modules/nuxt-speedkit/module.js:51:9)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:235:34)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1846:43)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
  at startup (internal/bootstrap/node.js:283:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by gerasimovs** [comment]
Oh sorry, I think I understand what the problem is. Tomorrow I will try to look and unsubscribe. Build locally without errors, version node (v10.23.3) is different on the server

**Comment by suinly** [comment]
Hello. I have the same error. Is there a solution?

**Comment by gerasimovs** [comment]
> Привет. У меня такая же ошибка. Есть решение?
> 
> ```
> node -v
> v10.24.0
> ```
> 
> ```
> "nuxt-speedkit": "^1.2.5"
> ```

https://github.com/GrabarzUndPartner/nuxt-speedkit#requirements
You need install NodeJs version 12+

**Comment by suinly** [comment]
> You need install NodeJs version 12+

Thanks, it works.
