### ISSUE TITLE
Incorrect attribute for the style element

### ISSUE THREAD

**Issue by gerasimovs** [GrabarzUndPartner/nuxt-speedkit#274]
https://github.com/GrabarzUndPartner/nuxt-speedkit/blob/26078e314fbab1989a05cc1623b207403b57fed3/lib/utils/description.js#L35

In the service for checking the validity of the layout (https://validator.w3.org/), it gives errors:
`Warning: The type attribute for the style element is not needed and should be omitted.`

**Comment by StephanGerbeth** [comment]
it is only a warning ;). We didn't know that the type attribute on a style tag is a antipattern.
We plan to fix it in the next release and give you some feedback.

Cheers
Stephan

**Comment by StephanGerbeth** [comment]
is done
