### ISSUE TITLE
Cannot read property 'matchMedia' of null

### ISSUE THREAD

**Issue by StirStudios** [GrabarzUndPartner/nuxt-speedkit#293]
**Describe the bug**
In dev mode I see the message 'nuxt-speedkit added module @nuxt/image'. Local starts as usual. Then when I run yarn build, then yarn start I get the following error:

` ERROR  Cannot read property 'matchMedia' of null

  at printObserver (node_modules/@nuxt/image/dist/runtime/image.js:205:0)
  at image_createObserver (node_modules/@nuxt/image/dist/runtime/image.js:238:0)
  at createImage (node_modules/@nuxt/image/dist/runtime/image.js:184:0)
  at _nuxt_image (.nuxt/image.js:29:0)
  at createApp (.nuxt/index.js:230:0)
  at async module.exports.__webpack_exports__.default (.nuxt/server.js:81:0)`

**To Reproduce**
1. Install module
2. Add 'nuxt-speedkit' to modules inside nuxt.config.js
3. Run yarn build
4. Run yarn start

**Work Around**
Steps to workaround the issue:
1. Install @nuxt/image
2. Run yarn build
3. Run yarn start

As a side note we don't use nuxt/image as we run everything through keyCDN.

**Nuxt Version**
2.15.6

**Comment by ThornWalli** [comment]
Hi,

do you have a sample configuration for the `SpeedkitPicture`?

**Comment by StirStudios** [comment]
Hi @ThornWalli we don't use that either. We were just testing the module to see if there were any improvements out the door. So all code was left alone. We followed the general config: https://nuxt-speedkit.grabarzundpartner.dev/setup and removed the fonts. We let the CMS take care of the images entirely.

**Comment by ThornWalli** [comment]
I took a close look, the problem seems to be that the `window` variable contains `null` on the server side. 

In `nuxt/image` is checked for `undefined` which is the default behavior of `window` variable server-side.

![image](https://user-images.githubusercontent.com/8287751/118399854-66561d00-b65f-11eb-831e-8919c2fe4a8d.png)

A nice example for not using `global` instead of `window`.
