### ISSUE TITLE
Missing comma from 'Example Configuration'

### ISSUE THREAD

**Issue by Hextar** [GrabarzUndPartner/nuxt-speedkit#368]
**Describe the bug**

**To Reproduce**
1. Go to page 'https://nuxt-speedkit.grabarzundpartner.dev/setup'
2. Copy paste the Example Configuration content in a nuxt.config.js
3. before the property 'componentAutoImport' there's a missing comma

**Expected behavior**
The configs should be copy-pastable with no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8740725/139711176-f59d9e33-8455-4f77-9fd4-aad80ea65dff.png)

**Comment by ThornWalli** [comment]
Thanks! :)
