### ISSUE TITLE
How do i fix Nuxt Warning 'nuxt build finished but did not exit after 5s'?

### ISSUE THREAD

**Issue by gitamgadtaula** [GrabarzUndPartner/nuxt-speedkit#540]
**Describe the bug**
╭───────────────────────────╮
│ │
│ ⚠ Nuxt Warning │
│ │
│ The command 'nuxt build' finished but did not exit after 5s │
│ │
│ This is most likely not caused by a bug in Nuxt.js │
│ │
│ Make sure to cleanup all timers and listeners you or your │
│ plugins/modules start. │
│ Nuxt.js will now force exit │
│ │
│ DeprecationWarning: Starting with Nuxt version 3 this will . │
│ be a fatal error │
│
╰───────────────────────────╯

Using nuxt-speedkit as a module gives me this error. Is there any workaround to solve this ?

**Comment by gitamgadtaula** [comment]
Hello @ThornWalli ,

I am working on a project with Nuxt and I am getting this issue; I am using fully SPA mode with ssr:false and I haven't used anything like firebase (saw a thread with same issue with firebase [.](https://github.com/nuxt/nuxt.js/issues/5669) . My team considers this to be a serious issue and I am finding hard time figuring out whats wrong. Unfortunately I cannot share my code but could you please give me a general idea of what might be happening and why would the issue occur? I am using few nuxt modules like 'Auth-next, google-analytics, nuxt-axios, nuxt-speedkit' and few others. I have couple of middlewares too but they are pretty simple and they don't have any timers; neither do any plugins.

this is my build configuration


```
build: {
    parallel: false,
    cache: true,
    hardSource: true,
    transpile: [/^element-ui/, /^vue2-google-maps($|\/)/],
    // maxChunkSize: 100000,
    babel: {
      compact: true,
    },
    extend(config, { isDev, isClient }) {
      // config.resolve.alias['chart.js'] = 'chart.js/dist/Chart.js'
      if (isClient && !isDev) {
        config.optimization.splitChunks.maxSize = 250000;
        config.performance.hints = false;
        config.devtool = false;
      }
    },
    // analyze: true,
    // parallel: false,
    // cache: true,
    // hardSource: true,
  },
 modules: [
    "@nuxtjs/axios", "@nuxtjs/auth-next",
    'nuxt-speedkit'
  ],
 speedkit: {
    detection: {
      performance: true,
      browserSupport: true
    },
    performanceMetrics: {
      device: {
        hardwareConcurrency: { min: 2, max: 48 },
        deviceMemory: { min: 2 }
      },
      timing: {
        fcp: 800,
        dcl: 1200
      },
      lighthouseDetectionByUserAgent: false
    }
  }
```
Toggling parallel option didn't help either. Really stuck with this one.

**Comment by ThornWalli** [comment]
@gitamgadtaula 

I think your problem is the SPA mode. `nuxt-speedkit` and the included `@nuxt/image` is for `ssr` and `server` mode.

- `nuxt-speedkit` needs the static markup, because there are the preloads included for the fast pageload only so you can get good pagespeed.
- `@nuxt/image` must be used in `ssr` or `server` mode. Here is nothing more to SPA https://image.nuxtjs.org/getting-started/installation

Your imports for `Chart.js`, `element-ui` and `vue2-google-maps` are async?

e.g.
```
const ChartJs = await import('chars.js');
```

If not, this might not be a reason why the build takes long.

Is there anything wrong with the ssr approach?

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
