### ISSUE TITLE
Cannot start app with nuxt-speedkit

### ISSUE THREAD

**Issue by preetecool** [GrabarzUndPartner/nuxt-speedkit#546]
I am getting a bug upon setup. 

1) Installation `npm i nuxt-speedkit`
2) Inserted 'nuxt-speedkit' in the modules array in  nuxt.config.js 
3) Inserted speedkit object in nuxt.config.js
4) Issue: When trying to `npm run dev` I get an error "Could not compile template ~/website/node_modules/nuxt-speedkit/templates/plugin.js"

I was trying to search Google for a possible answer and it seems this issue is relevant to other projects: https://codesandbox.io/s/murlf?file=/package.json:508-517. This project also shows the same error "Could not compile template..".

Cheers!

**Comment by preetecool** [comment]
Is there a way with node 12?

**Comment by ThornWalli** [comment]
You'll get an update soon :) Then it should also work with `12`.

But you should change to version `14` in the future 🙂

https://github.com/GrabarzUndPartner/nuxt-speedkit/pull/550

**Comment by preetecool** [comment]
@ThornWalli Great, thank you! The codebase I'm working with uses node 12.

**Comment by ThornWalli** [comment]
@preetecool https://nodejs.org/en/about/releases/#releases 😉
