### ISSUE TITLE
Not working with @nuxt/image while provider is defined

### ISSUE THREAD

**Issue by Amar1432** [GrabarzUndPartner/nuxt-speedkit#557]
I am using nuxt/image with gumlet provider in my project, but if i try to use nuxt speedkit with it then it throws an error.
Although it works if i don't define the provider properties in image block in nuxt.config.js but when i do, the project won't even start neither in dev mode nor in production mode.

I am getting this error:-

 FATAL  Cannot use 'in' operator to search for 'youtube' in undefined                                                                             10:52:43

  at node_modules/nuxt-speedkit/module.js:26:72
  at Array.find (<anonymous>)
  at node_modules/nuxt-speedkit/module.js:26:50
  at node_modules/hable/dist/hable.js:1:990
  at node_modules/hable/dist/hable.js:1:208
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:61:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)

   ╭──────────────────────────────────────────────────────────────────────────────╮
   │                                                                              │
   │   ✖ Nuxt Fatal Error                                                         │
   │                                                                              │
   │   TypeError: Cannot use 'in' operator to search for 'youtube' in undefined   │
   │                                                                              │
   ╰──────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! satya-paul@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the satya-paul@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amarjeet/.npm/_logs/2022-04-05T05_22_43_843Z-debug.log

here is my speedkit and nuxt image config:-

  speedkit: {
    detection: {
      performance: true,
      browserSupport: true,
    },

    performanceMetrics: {
      device: {
        hardwareConcurrency: { min: 2, max: 48 },
        deviceMemory: { min: 2 },
      },
      timing: {
        fcp: 800,
        dcl: 1200,
      },
    },

    componentAutoImport: false,
    componentPrefix: undefined,

    /**
     * IntersectionObserver rootMargin for Compoennts and Assets
     */
    lazyOffset: {
      component: "0%",
      asset: "0%",
    },

    loader: {
      dataUri: null,
      size: "100px",
      backgroundColor: "grey",
    },
  },

  image: {
    gumlet: {
      baseURL: "https://satya.gumlet.io",
    },
  },

**Comment by ThornWalli** [comment]
Hello @Amar1432 ,

you can install the latest `nuxt-speedkit` version.

Note that you need a current `@nuxt/image` version for the provider you want to use.

This is unfortunately not really usable yet for some reasons, so we still have an open PR.

But to get around all this you can set an `overrides` in the `package.json`. There you can update the `@nuxt/image` version, then the `IPX` must be set to an older version.

- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
- https://nuxt-speedkit.grabarzundpartner.dev/caveats#use-latest-nuxtimage-version
- https://nuxt-speedkit.grabarzundpartner.dev/components/speedkit-image#source

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
