### ISSUE TITLE
Form not loading except when changing tabs

### ISSUE THREAD

**Issue by preetecool** [GrabarzUndPartner/nuxt-speedkit#574]
Hello. 

I am encountering a problem with Chrome (uninstalling nuxt-speedkit or downgrading to v1 the problem is no longer there), and forms. When I try to load a form on my website it takes a very long time before loading the form. The form immediately loads if I change tabs. The problem seems to be specific to Chrome. No problems on Safari or Firefox.

What type of issue is this? 

Thanks.

**Comment by ThornWalli** [comment]
Hello @preetecool,

what exactly do you mean by `form`? A submit with method POST or something?

Are you running in dev mode?

Do you have a code example?

**Comment by preetecool** [comment]
Seems the problem wasn't necessarily the form. I was able to circumvent the issue by removing the loading spinner from that particular page, and using the text "Loading...". The spinner was not letting Vue lifecycle go to mounted which is where I have a flag to signal the spinner loader to stop displaying. The spinner loader is its own component and is using scss.

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
