### ISSUE TITLE
Docs: Link to edit broken

### ISSUE THREAD

**Issue by Triloworld** [GrabarzUndPartner/nuxt-speedkit#641]
Steps to reproduce:
1. Go to page: https://nuxt-speedkit.grabarzundpartner.dev/caveats
2. Click: [Edit this page on GitHub](https://github.com/GrabarzUndPartner/nuxt-speedkit/edit/main/docs/content/en/caveats.md)
3. We get 404

Solution: add v2 to links 
https://github.com/GrabarzUndPartner/nuxt-speedkit/edit/main/docs/content/v2/en/caveats.md

**Comment by ThornWalli** [comment]
Thanks! Have fixed it 🙂
