### ISSUE TITLE
It's not possible to set crossorigin undefined 

### ISSUE THREAD

**Issue by Quineone** [GrabarzUndPartner/nuxt-speedkit#653]
**Describe the bug**
Sometimes we don't want the `crossorigin` property for the img tag.
Because this, we can't do that
```js
crossorigin: options.crossorigin || scope.nuxt.options.render.crossorigin || 'anonymous',
```

**Comment by StephanGerbeth** [comment]
Hi @Quineone 

if we understand you correctly, you want to be able to disable and configure the crossorigin specification on a single img componente. Is that correct? Or do you want to be able to disable it globally?

Cheers
Stephan

**Comment by Quineone** [comment]
I want to disable it globally

**Comment by ThornWalli** [comment]
@Quineone `crossorigin` can now be disabled via module option or directly on `SpeedkitImage` or `SpeedkitPicture`.

https://nuxt-speedkit.grabarzundpartner.dev/options#crossorigin
https://nuxt-speedkit.grabarzundpartner.dev/components/speedkit-image#crossorigin
https://nuxt-speedkit.grabarzundpartner.dev/components/speedkit-picture#crossorigin
