### ISSUE TITLE
@nuxt/image - Optional

### ISSUE THREAD

**Issue by StirStudios** [GrabarzUndPartner/nuxt-speedkit#654]
Is there any chance we can have this option configurable? There are times when a CMS takes care of this along with CDN. So the image optimizations are never used.

**Proposed Solution**
It would be great if you could disable/enable the image feature when needed. This way you are not loading unneeded modules.

**Errors**
`[nuxt-speedkit] added module @nuxt/image, for more configuration learn more at https://image.nuxtjs.org/setup#configure`                                                                                                                         

`ERROR  [@nuxt/image] ipx is an optional dependency for local image optimization and is not properly installed. Please try npm install or yarn install again.`

`ERROR  TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.`                                                                                                                        

`at node_modules/@nuxt/image/dist/module.cjs:112:13`

**Comment by ThornWalli** [comment]
Hello @StirStudios,

I understand, but this requires the use of the components `SpeedkitPicture` and `SpeedkitImage` and others.

These currently only work with `@nuxt/image`.

Are you using the module components or a simple integration? and what version of **Node** are you using?

**Comment by StirStudios** [comment]
Hi @ThornWalli,

We are currently using a simple integration and we do not use `SpeedkitPicture` or 'SpeedkitImage'

Node.js => v16.15.0

`[
      'nuxt-speedkit',
      {
        speedkit: {
          detection: {
            performance: true,
            browserSupport: true,
          },
          performanceMetrics: {
            device: {
              hardwareConcurrency: { min: 2, max: 48 },
              deviceMemory: { min: 2 },
            },
            timing: {
              fcp: 800,
              dcl: 1200,
            },
          },
          componentAutoImport: false,
          componentPrefix: undefined,
          lazyOffset: {
            component: '0%',
            asset: '0%',
          },
        },
      },
    ]`

**Comment by ThornWalli** [comment]
Have created a PR for this topic.

But this is only the first step, in the future for not using `@nuxt/image` the two components should also be usable manually.

**Comment by StirStudios** [comment]
Thanks so much for being open to the possibilities. Such an awesome module and has helped us immensely with Google Lighthouse scores.

**Comment by ThornWalli** [comment]
@StirStudios is now included in the new release `2.0.15`. 

https://nuxt-speedkit.grabarzundpartner.dev/options#disablenuxtimage

**Comment by StirStudios** [comment]
What a rockstar! Keep up the awesome work!
