### ISSUE TITLE
Cannot add property data-fetch-key, object is not extensible

### ISSUE THREAD

**Issue by frossigneux** [GrabarzUndPartner/nuxt-speedkit#663]
Nuxt version:
2.15.7

Node version:
v16.13.0

No problem using `yarn dev`.
Using `yarn build && yarn start` fails with:

```
 ERROR  Cannot add property data-fetch-key, object is not extensible                                                                                                                  18:55:21

  at a.serverPrefetch (.nuxt/mixins/fetch.server.js:25:0)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Promise.all (index 0)
```

The `fetch.server.js` fails here:
```
  // Add data-fetch-key on parent element of Component
  const attrs = this.$vnode.data.attrs = this.$vnode.data.attrs || {}
  attrs['data-fetch-key'] = this._fetchKey
```

**Comment by ThornWalli** [comment]
Hello @frossigneux,

do you get the error even if you don't include `nuxt-speedkit` and use a component with a `fetch` and custom `fetchKey`?

Is very strange that the `attrs` is freeze.

**Comment by frossigneux** [comment]
Hello, I get error only if I use speedkit (I tested the last two speedkit version... same bug).
My project is quite big, I modified all my imports to switch from nuxt auto-import to speedkit import system.

**Comment by frossigneux** [comment]
https://github.com/vitejs/vite/issues/717
Here is a similar bug...

**Comment by frossigneux** [comment]
@ThornWalli The bug occurs only on pages using fetch in their components. Using the fetch in page is ok!

I get error only if I include `nuxt-speedkit`.
Using a custom `fetchKey` is working fine without `nuxt-speedkit`.

**Comment by ThornWalli** [comment]
@frossigneux I tried to reproduce something using your dependencies. Unfortunately I haven't found the error yet. 

Could you share your `nuxt.config`?

**Comment by frossigneux** [comment]
Here is my nuxt.config: https://pastebin.com/raw/uJg8JdUe
I continued the investigation, trying to modify nuxt-speedkit-example to reproduce the bug, without success: using a fetch method in nuxt-speedkit-example components works fine (I thought it might be related to that).
In my code, I use static import in every component. And hydrate in pages and layouts.

**Comment by frossigneux** [comment]
Here is my nuxt.config: https://pastebin.com/raw/xd3bkySy
I continued the investigation, trying to modify nuxt-speedkit-example to reproduce the bug, without success: using a fetch method in nuxt-speedkit-example components works fine (I thought it might be related to that).
In my code, I use static import in every component. And hydrate in pages and layouts.

**Comment by frossigneux** [comment]
I removed all my components, pages and layout, excepted one minimal layout / page / component.
And I confirm that when I add:
```
<script>
export default {
  async fetch() {
    await new Promise((resolve) => setTimeout(resolve, 1000))
  },
}
</script>
```
in my component, the bug occurs.

**Comment by ThornWalli** [comment]
Very good 🙂 Now the analysis of the problem begins.

Now you need to reduce the modules and plugins.

Feel a `race condition` with another `vue plugin` or `nuxt/module` etc.

**Comment by frossigneux** [comment]
@ThornWalli I reproduced the bug very simply using the `nuxt-speedkit-example`:

Just do this:
```
diff --git a/components/SpeedkitPicture.vue b/components/SpeedkitPicture.vue
index e4cd357..0da9c67 100644
--- a/components/SpeedkitPicture.vue
+++ b/components/SpeedkitPicture.vue
@@ -16,6 +16,9 @@ export default {
   inheritAttrs: false,
   mounted () {
     objectFitImages();
+  },
+  fetch () {
+    console.log('Foo');
   }
 };
 
diff --git a/nuxt.config.js b/nuxt.config.js
index 2390c35..0664adb 100644
--- a/nuxt.config.js
+++ b/nuxt.config.js
@@ -2,7 +2,7 @@ import pkg from './package.json';
 
 export default {
   // Target: https://go.nuxtjs.dev/config-target
-  target: 'static',
+  // target: 'static',
 
   server: {
     host: getHost(),
diff --git a/pages/index.vue b/pages/index.vue
index f6bd415..3be3a77 100644
--- a/pages/index.vue
+++ b/pages/index.vue
@@ -3,7 +3,7 @@
     <!-- critical prop for critical components: https://nuxt-speedkit.grabarzundpartner.dev/usage#critical-prop-for-critical-components -->
     <intro critical />
     <DirectiveVFontA />
-    <SpeedkitPicture v-bind="speedkitPictureLight" />
+    <SpeedkitPicture />
     <DirectiveVFontB />
     <SpeedkitPicture v-bind="speedkitPictureDark" />
     <SpeedkitIframe />

```
Then run it with `yarn build && yarn start`.
Then get the error:
```
Foo                                                                                                                                                                                   12:44:16

 ERROR  Cannot add property data-fetch-key, object is not extensible                                                                                                                  12:44:16

  at i.serverPrefetch (.nuxt/mixins/fetch.server.js:25:0)
  at async Promise.all (index 0)
```

Removing one (or the two) v-bind on the two SpeedkitPicture triggers the bug!

**Comment by ThornWalli** [comment]
Do you work with `speedkitHydrate`?

I emptied the example except for including `nuxt-speedkit` and importing the component `'@/components/SpeedkitPicture` with your customizations but no `SpeedkitPicture` included. Should be now only `speedkitHydrate` and get there the error. 

Will have a look at it...

**Comment by ThornWalli** [comment]
@frossigneux Can you replace the lines with the in your project?

Suspect the problem here. But it only brings something if you have `speedkitHydrate` in use 🙂

https://github.com/GrabarzUndPartner/nuxt-speedkit/blob/85f875fc39984243ecba41b7e2b9c8bd2397fe86/lib/hydrate.js#L9-L24


**Replace with:**

```javascript
export default (component) => {
  if (isDev || process.server) {
    // important for clean hot reload in dev
    return component;
  }

  return ({
    render (h) {
      return h(wrap(component, idleExecuteResolve), {
        attrs: this.$attrs,
        on: this.$listeners,
        scopedSlots: this.$scopedSlots
      }, this.$slots.default);
    }
  });
};
```

**Comment by frossigneux** [comment]
Yes, your fix fixes the issue in `nuxt-speedkit-example`!
On my project I use speedkitHydrate on all pages and layouts, and in components I use static imports as recommended in the speedkit documentation.
What is the next step? Do you plan to publish a fix in nuxt-speedkit?
Thanks

**Comment by frossigneux** [comment]
@ThornWalli Yes, your fix fixes the issue in `nuxt-speedkit-example`!
On my project I use speedkitHydrate on all pages and layouts, and in components I use static imports as recommended in the speedkit documentation.
What is the next step? Do you plan to publish a fix in nuxt-speedkit?
Thanks

**Comment by ThornWalli** [comment]
Must be fixed :) But still need some time to think...

**Comment by ThornWalli** [comment]
@frossigneux Have now merged the PR 🙂 A new version is now published.
