### ISSUE TITLE
Inconsistent behavior between dev and prod server mode

### ISSUE THREAD

**Issue by frossigneux** [GrabarzUndPartner/nuxt-speedkit#689]
Nuxt version:
2.15.7

Node version:
v16.13.0

No problem using `yarn dev`.
Using `yarn build && yarn start` gives unexpected results for imported components using speedkitHydrate.
They fetch method in those components are trigerred in loop on some of them, and don't know why.
In a first time I tought it was on property change or something like that (although usually changing a property does not retrigger fetch), but even after checking properties are not changed using a "watch" on them, I still observe the unexpected fetch loop (querying in my case an API).

Before digging more, what is supposed to trigger fetch loop in components?

**Comment by ThornWalli** [comment]
Hello @frossigneux,

the `fetch` loop is very strange.

Basically there is no difference between `dev` and `server` mode in the initialization of the components server-side.

https://github.com/GrabarzUndPartner/nuxt-speedkit/blob/77155cda44d41035f8ab297d02e3ac1ec4906882/lib/hydrate.js#L9-L23

In both cases, the component is passed directly in `server` mode. Client side the component is initialized with `vue-lazy-hydration`.

Does it happen in `server` the loop or in `client`?

Can you reproduce this in an empty project with a very simple example?

**Comment by frossigneux** [comment]
Ok, here is a minimal example to reproduce inconsistent behavior.

Component `Child.vue`:
```
<template>
  <v-card flat>Child: {{ loading }}</v-card>
</template>

<script>
export default {
  props: {
    loading: {
      type: Boolean,
      required: true,
    },
  },
  fetch() {
    this.$emit('update:loading', true)
    console.log('FETCH CHILD')
    this.$emit('update:loading', false)
  },
}
</script>
```

Page `page.vue`:
```
<template>
  <v-container>
    Parent: {{ loading }}
    <Child
      :loading.sync="loading"
    />
  </v-container>
</template>

<script>
import speedkitHydrate from 'nuxt-speedkit/hydrate'

export default {
  components: {
    Child: speedkitHydrate(() => import('@/components/Child')),
  },
  data() {
    return {
      loading: true,
    }
  },
}
</script>
```

Browser rendering output using `yarn dev` (no fetch loop):
```
Parent: false
Child: false
```

Browser rendering output using `yarn build && yarn start` (fetch loop):
`Parent: true`

Browser rendering output using regular import instead of speedkitHydrate and dev or prod server mode (no fetch loop):
```
Parent: false
Child: false
```

Then, the behavior is different using speedkitHydrate, `fetch` is triggered as soon as a property is changed.

**Comment by frossigneux** [comment]
The property change is even not required to triggers the bug:

Component `Child.vue`:
```
<template>
  <v-card flat>Child}</v-card>
</template>

<script>
export default {
  fetch() {
    this.$emit('loading', true)
    console.log('FETCH CHILD')
    this.$emit('loading', false)
  },
}
</script>
```


Page `page.vue`:
```
<template>
  <v-container>
    Parent: {{ loading }}
    <child
      @loading="
        (value) => {
          loading = value
        }
      "
    />
  </v-container>
</template>

<script>
import speedkitHydrate from 'nuxt-speedkit/hydrate'

export default {
  components: {
    Child: speedkitHydrate(() => import('@/components/Child')),
  },
  data() {
    return {
      loading: true,
    }
  },
}
</script>
```

Just emitting an event, changing something in the parent page, triggers the infinite fetch loop...

**Comment by frossigneux** [comment]
Ok, here is a minimal example to reproduce inconsistent behavior.

Component `Child.vue`:
```
<template>
  <v-card flat>Child</v-card>
</template>

<script>
export default {
  fetch() {
    this.$emit('loading', true)
    console.log('FETCH CHILD')
    this.$emit('loading', false)
  },
}
</script>
```

Page `page.vue`:
```
<template>
  <v-container>
    Parent: {{ loading }}
    <child
      @loading="
        (value) => {
          loading = value
        }
      "
    />
  </v-container>
</template>

<script>
import speedkitHydrate from 'nuxt-speedkit/hydrate'

export default {
  components: {
    Child: speedkitHydrate(() => import('@/components/Child')),
  },
  data() {
    return {
      loading: false,
    }
  },
}
</script>
```

Browser rendering output using `yarn dev`: no fetch loop.
Browser rendering output using `yarn build && yarn start`: fetch loop!
Browser rendering output using regular import instead of speedkitHydrate and dev or prod server mode: no fetch loop.
So there is a problem with speedkitHydrate and prod mode. I always tested by navigating to the test page indirectly.

However, if we replace in parent:
`Parent: {{ loading }}
`
by
`Parent`

there is no more infinite loop.

Other thing: if I emit only one event, there is no more infinite fetch loop neither!

The bug is related to the rendering of parents in the case of multiple events.

@ThornWalli Thanks for your help!

**Comment by frossigneux** [comment]
@ThornWalli Do you have the same bug with my minimal example? Thanks

**Comment by ThornWalli** [comment]
@frossigneux Could understand it and probably also solve. 
But now I have to think about the change again. In principle, nothing speaks against it.

**Comment by ThornWalli** [comment]
@frossigneux Have now a `beta` release, so you can test it.

https://www.npmjs.com/package/nuxt-speedkit/v/2.0.21-beta.1

**Comment by ThornWalli** [comment]
Is included in the latest version.
