### ISSUE TITLE
Adsense support required

### ISSUE THREAD

**Issue by Croodo** [GrabarzUndPartner/nuxt-speedkit#692]
This module works great, but while using AdSense module there is no improvement. 
Please consider adding AdSense module support if possible.

**Comment by ThornWalli** [comment]
Hello @Croodo,

Is this about this module? (https://github.com/nuxt-community/google-adsense-module)

Unfortunately there is nothing we can do. 

There must be customizations in the module itself. 

There should be a possibility, with which the user himself controls when the required scripts are loaded.

The simplest solution would be to set the scripts in the head only in the `client`. 
In the SSR these have nothing to look for and influences the loading behavior.

https://github.com/nuxt-community/google-adsense-module/blob/ac541311b710503562918bc2018d1117f37a7c45/src/index.ts#L62-L67

**Comment by ThornWalli** [comment]
Close the issue for now, but can be reopened if used.
