### ISSUE TITLE
Hydration not work if page not visible and not active tab

### ISSUE THREAD

**Issue by deasurv** [GrabarzUndPartner/nuxt-speedkit#735]
**Describe the bug**
hydration after hard reload will not happened at all if you opened website and before see any content, immediately switch to any other browser tab page. it also happened to me on android google chrome.

**To Reproduce**
1. Scroll down and Go to 'Demos' section of Nuxt Speedkit Introduction
2. Open [Grabarz & Partner](https://grabarzundpartner.de/) website in new tab with middle click of mouse.
3. After few moments (e.g. few seconds) that sure server-side rendered content received and loaded switch to [Grabarz & Partner](https://grabarzundpartner.de/) tab.
4. You will notice that video of hero section doesn't play. also with scroll down any image and content will not show.

**Expected behavior**
Hydration on client side must happen even website tab/window is not visible and not active tab or loses focus.

**Screenshots**
https://imgur.com/a/uOc7f33

**Desktop (please complete the following information):**
 - OS: Windows NT 10.0; Win64; x64
 - Browser: Chrome 108.0.5359.73
 - Nuxt: 2.15.8
 - Nuxt-speedkit: 2.1.2

**Smartphone (please complete the following information):**
 - Device: SM-G781B
 - OS: Android 12
 - Browser: Chrome 108.0.5359.79

**Comment by arincon9** [comment]
Hey @deasurv, were you able to fix this issue or find a workaround solution?

**Comment by deasurv** [comment]
Hi @arincon9.
not actually, but I figured out bug happened due to usage of **requestAnimationFrame** in code for detecting reduced bandwidth/weak hardware.
Because **requestAnimationFrame** will pause the callback function passed to it from running, when web page tab is inactive/invisible for battery and cpu improvement.
If you want you can place **<SpeedkitLayer />** component in your app, so the popup will show to select continue app initialization or cancel it.

Let me know if you find a solution.
Thanks!

**Comment by ThornWalli** [comment]
Fixed the problem. If `document.hidden` is `true`, waits for `visibilitychange` and then initializes.

Can be tested with `nuxt-speedkit@beta`.

**Comment by deasurv** [comment]
Hey @ThornWalli.
updated to last version, bug fixed on Chrome Desktop, but still there on Android version.
to ensure, I tested on two variant phones with android 12 and 13 and even on Opera mobile browser.

**Comment by ThornWalli** [comment]
Hello @deasurv,

1. with `firefox` on `android` both `document.hidden` and `document.visibilityChange` was on `visible`, although opened in new tab. Here the initialization ran into a timeout which was not caught, thus it stopped.
2. both `chrome` and `opera` (https://play.google.com/store/apps/details?id=com.opera.browser) run through on `android` for me. 

I made another change, can you test this again?

**Comment by deasurv** [comment]
@ThornWalli
tried latest beta. JS initialized on all mentioned browsers as expected. But when I ran [PageSpeed in](https://pagespeed.web.dev/), project achieve same past scores when nuxt-speedkit was not installed!

**Comment by ThornWalli** [comment]
I took back the initialization change. 
This is a place that we can not change, the switch is needed. It is an important component except for the performance check.

The problem is a bit tricky.

With opening in a separate tab the case `nuxt-speedkit-message-weak-hardware` can occur.

This is intentional with PageSpeed but can be a side effect when opening a tab in the background. (Example Firefox (Android), this did not give me the `document.hidden` set or `visibilityChange` `hidden` is, accordingly one gets then in the together play with `requestIdleCallback` and `requestAnimationFrame` false values).

In this situation a solution must be found with the `SpeedkitLayer` with `nuxt-speedkit-message-weak-hardware` or https://nuxt-speedkit.grabarzundpartner.dev/caveats#prevent-speedindex_of_zero--and-no_lcp-.


Mentally the problem would be gone if we just start the initialization at `document.hidden === true` without a performance check. But I can't really get along with this idea.

**Comment by arincon9** [comment]
Thank you both for looking into and testing this, I look forward to further updates on this issue. For now my team and I will be foregoing using Nuxt-Speedkit.

**Comment by ThornWalli** [comment]
@deasurv Added again the possibility to force the initialization.

As long as browser supports this [document.visibilityState](https://caniuse.com/?search=document.visibilitydocument.visibilityState%20%3D%3D%3D%20%27hidden%27) and the `hidden` applies in the background tab is initialized immediately without Idle/AnimationFrame analysis.

```javascript
{
  head () {
    return {
      script: [
        {
          hid: 'force-init-script',
          innerHTML: `if (document.visibilityState === 'hidden') { window.__NUXT_SPEEDKIT_FORCE_INIT__ = true; }`
        }
      ],
      __dangerouslyDisableSanitizers: [
        'script'
      ]
    };
  }
}
```

**Comment by ThornWalli** [comment]
Missing initialization on hidden tab is published.

The issue with initialization can also have other backgrounds, see here https://github.com/GrabarzUndPartner/nuxt-speedkit/issues/752
