### ISSUE TITLE
Weak hardware message at Macbook Pro 2019

### ISSUE THREAD

**Issue by dennisgroot** [GrabarzUndPartner/nuxt-speedkit#752]
Hello, the plugin works really well and our pagespeed score improved a lot, but the infolayer with the weak hardware message appears really fast. Even at a normal Macbook Pro from 2019. 

I tried to set hardwareConcurrency and deviceMemory at the lowest value, but the message is still showing.
```
performanceMetrics: {
      device: {
        hardwareConcurrency: { min: 1, max: 48 },
        deviceMemory: { min: 1 }
      }
 }
```

Is is possible to set the hardware requirements lower? Or if not, is it possible to force initialize the page at all devices? 

Thanks!

**Comment by ThornWalli** [comment]
Hello @dennisgroot,

suspect the message directly when matching the `requestAnimationFrame` and `requestIdleCallback` duration. It is calculated average based on the respective trigger times on a duration of `1000ms`, if that falls below a threshold, the message comes.

I have two options at the moment :)

1. do you have a video or something that could interfere initially? 

> I had a problem with a video before the DOM replacement. Then I set the sources only in the client, so after the initialization.

2. there is the option `runOptions.threshold`, there you can test to reduce the threshold in small steps.

Keep in mind that this can break the pagespeed test. 

```js
{
  speedkit: {
    runOptions: { maxTime: 1000, threshold: 0.65 }
  }
}
```

**Comment by dennisgroot** [comment]
Hi @ThornWalli 

Thanks for the quick answer!

Yes I use some videos on the page, but they are all lazyloaded.  Check out the site here > https://raadhuis.com/
Maybe you have an other suggestion if you check the site in action. 

I tried also the second option, but as you said it breaks the pagespeed score.

Thank you so much for your time!

**Comment by ThornWalli** [comment]
Strange, generally looks quite good :)

Do you have the possibility to activate `gtm-script` in the client first? 
So script tag disappears on the SSR.

```html
<script data-n-head="ssr" data-hid="gtm-script">if(!window._gtm_init){window._gtm_init=1;(function(w,n,d,m,e,p){w[d]=(w[d]==1||n[d]=='yes'||n[d]==1||n[m]==1||(w[e]&&w[e][p]&&w[e][p]()))? 1:0})(window,navigator,'doNotTrack','msDoNotTrack','external','msTrackingProtectionEnabled');(function(w,d,s,l,x,y){w[x]={};w._gtm_inject=function(i){if(w. doNotTrack||w[x][i])return;w[x][i]=1;w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s);j.defer=true;j. src='https://www.googletagmanager.com/gtm.js?id='+i;f.parentNode.insertBefore(j,f);};w[y]('xxx')})(window,document,'script','dataLayer','_gtm_ids','_gtm_inject')}</script>
```

**Comment by dennisgroot** [comment]
@ThornWalli 

GTM is added via `@nuxtjs/gtm`. I don't know if that's possible.

**Comment by dennisgroot** [comment]
@ThornWalli Thanks, made some progress!

**Comment by ThornWalli** [comment]
@dennisgroot Did it work?
