### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by EmilyFlocc** [GrabarzUndPartner/nuxt-speedkit#766]
Hey, love this package and just wondering if you have plans to make it Nuxt 3 compatible? If so, roughly when will it be?

**Comment by ThornWalli** [comment]
Hello @EmilyFlocc,

we are on it, but moving slowly.

Unfortunately you run into some problems. 
Here is an [issue](https://github.com/GrabarzUndPartner/nuxt-speedkit/issues/542) about the migration 

Currently we are struggling more with `vue@3` still ;)
