### ISSUE TITLE
Duplicate Styles

### ISSUE THREAD

**Issue by lgrnsh** [GrabarzUndPartner/nuxt-speedkit#811]
**Describe the bug**
Styles are loaded twice. All component style tags are scoped. Global styles are set in ```nuxt.config.js``` and are not imported anywhere else.
I don't quite understand if this is some Nuxt-Speedkit bug, or a bug in my project?

**Screenshots**
![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/86368375/c4f279cf-05de-463c-9b5c-7cbb1e77bc11)

![image_2023-05-10_10-32-45](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/86368375/f2ae2b7e-4184-4ae6-9e51-83b72dc24247)

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/86368375/e7c793b2-28a9-4d57-bc4e-57a8a3f20346)

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/86368375/852290a1-2162-4a7f-ad06-7340bfa130ef)

**Additional context**
Nuxt version 2.15.8, universal mode, ```extractCSS``` build option enabled, styles, variables and mixins are loaded from the following files.
```
css: [
    '@/assets/scss/style.scss'
],
styleResources: {
    scss: [
         '@/assets/scss/global.scss'
    ]
},
````

**Comment by StephanGerbeth** [comment]
I think its a bug in your project. Cause we write some inline styles but don't change the css config.
