### ISSUE TITLE
Unable to import after updating from 2.0.13 to 2.2.1

### ISSUE THREAD

**Issue by ilyalosinski** [GrabarzUndPartner/nuxt-speedkit#817]
I'm currently using the nuxt-speedkit package in my project and I've encountered some difficulties after recent updates. I have been trying to import specific components and files directly from the package like so:

```
import SpeedkitImage from 'nuxt-speedkit/components/SpeedkitImage';
import SpeedkitPicture from 'nuxt-speedkit/components/SpeedkitPicture';
import speedkitHydrate from 'nuxt-speedkit/hydrate';
```

Now I'm having this issue for all these imports:

`Unable to resolve path to module 'nuxt-speedkit/hydrate'.eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-unresolved.md)`

I've checked the new structure of the nuxt-speedkit package and it seems to have changed significantly, which may be causing the issue. I have tried adjusting the import paths to match the new structure, but I'm still encountering the same problem.

I'm using nuxt 2.15.8.

Could you please provide some guidance on how to import these specific components and files with the new package structure? Are direct file imports supported with the current version of nuxt-speedkit?

**Comment by ThornWalli** [comment]
This is an internal alias in `nuxt`.

And should work without any customization.

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/8287751/e77f763e-7b2e-4a70-8f33-146915b8f0a1)

**Comment by ilyalosinski** [comment]
It's interesting that I had to manually update my ESLint configuration, but now it's finally working correctly.

Nuxt recognizes your path, but ESLint does not. To resolve the path resolution issue, I added the following code to my ESLint configuration:

```
settings: {
  'import/resolver': {
    alias: {
      map: [
        ['#speedkit', './node_modules/nuxt-speedkit/src/runtime'],
      ],
      extensions: ['.js', '.mjs']
    }
  }
}
```

And now everything works as intended!

**Comment by ilyalosinski** [comment]
It's interesting that I had to manually update my ESLint configuration, but now it's finally working correctly.

Nuxt recognizes your path, but ESLint does not. To resolve the path resolution issue, I added the following code to my ESLint configuration:

```
settings: {
  'import/resolver': {
    alias: {
      map: [
        ['#speedkit', './node_modules/nuxt-speedkit/src/runtime'],
      ],
      extensions: ['.js', '.mjs']
    }
  }
}
```

And now everything works as intended!
