### ISSUE TITLE
speedkitHydate runtime error

### ISSUE THREAD

**Issue by bartlwojcik** [GrabarzUndPartner/nuxt-speedkit#836]
**Description**
After package installation and configuration I tried to use the `speedkitHydrate`, but when I import it I got this error:
```
ERROR in ./node_modules/nuxt-speedkit/runtime/hydrate.mjs 8:9-27
Can't import the named export 'hydrateWhenVisible' from non EcmaScript module (only default export is available)
```

**Reproduction**
1. Install `nuxt-speedkit` and add basic configuration
2. Import `speedkitHydrate` in a page file

**Expected behavior**
There should be no error

**Versions:**
 - `nuxt` 2.15.8
 - `nuxt-speedkit` 2.2.2

**Comment by ThornWalli** [comment]
Hello @bartlwojcik,

Which `node` version are you using?

Have you tried to include `vue-lazy-hydration` in the `build.transpile`?

Maybe also consider to update `nuxt` to `2.17.x`?

**Comment by bartlwojcik** [comment]
Hello @ThornWalli,

adding `vue-lazy-hydration` to the `build.transpile` didn't help, but updating `nuxt` and `vue` did.

Thank you for your help!
