### ISSUE TITLE
Speedkit DUPLICATES embedded <style> replacing absolute with relative paths for "public" paths on "generate" 

### ISSUE THREAD

**Issue by sbastias** [GrabarzUndPartner/nuxt-speedkit#877]
During `bun generate`, speedkit is re-embedding CSS, leading to double CSS in `<head>`, but also replaces absolute paths (for PUBLIC assets) with relative paths, breaking images on nested routes.

Create a Nuxt app with a nested route and in-component styles - see below:

/pages/service.vue (parent page)
```
<!-- /pages/service.vue -->
<template>

  <div class="subpage-container">

    <NuxtPage />
    
  </div>
</template>
```

/pages/service/interior.vue (child)
```
<!-- /pages/service/interior.vue -->
<template>

  <div class="subpage-container">

    <div class="row page-title" id="interior-title">
      <div class="row-content">
        <section>
          <h1>Page Title</h1>
        </section>
      </div>
    </div>
    
  </div>
</template>

<style>
#interior-title {
  background: url(/img/slider/kitchen-3.webp) no-repeat center;
  background-size: cover;
}
</style>
```

**Expected behavior**
Should only inject @font-face CSS, but it's embedding ALL page CSS (duplicating CSS rules), and with RELATIVE routes, breaking the absolute path for /public assets

I had to remove Speedkit to fix the issue - simply enabling the nuxt-speedkit module in nuxt.config.ts leads to Embed CSS File during generate...
<img width="332" alt="image" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/1007243/b341f9ec-6a43-46e3-a02c-1df811e850fe">

**Screenshots**
This is the CSS embedded by Nuxt - absolute path, correct! (on line 18)
<img width="558" alt="image" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/1007243/c22a0de1-f39b-44af-bd23-fc63080f03d3">

This is the `<style>` block started by Speedkit.... (on line 28, overruling the correct CSS...)
<img width="608" alt="image" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/1007243/23982938-d727-4104-8317-dd9821d58128">

...and the DUPLICATED CSS rule, with RELATIVE path in the same `<style>` block:
<img width="573" alt="image" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/1007243/4d8a5c71-d553-43fe-b4d6-3b5084441568">

- Operating System: Linux
- Node Version:     v18.13.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      devtools, runtimeConfig, dir, modules, app, speedkit, nitro
- Runtime Modules:  nuxt-speedkit@3.0.0-next.27
- Build Modules:    -

**Comment by ThornWalli** [comment]
Hello @sbastias,

1. the problem with the relative paths is now fixed, they are now relative to the style file.
2. CSS duplicates are removed. inlineSSRStyles' is deactivated. 
For the embedding of the CSS, the module takes care.
https://github.com/GrabarzUndPartner/nuxt-speedkit/blob/next/src/utils/preload.mjs

**Comment by sbastias** [comment]
Yes, I updated and re-instated nuxt-speedkit module and the extra CSS is gone on SSR generate! Well done - so fast. Thank you!
