### ISSUE TITLE
CORS Youtube Component

### ISSUE THREAD

**Issue by dissy123** [GrabarzUndPartner/nuxt-speedkit#888]
**Describe the bug**
i'm getting the following error when embedding the LazySpeedkitYoutube Component.

Access to image at 'https://img.youtube.com/vi/ckYCiB3tzR4/maxresdefault.jpg' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I'm just setting the url and the title: 

`<LazySpeedkitYoutube :url="props.data.url" :title="props.data.title" />`

The Image Url seems Correct

"nuxt": "^3.8.0",
"nuxt-speedkit": "3.0.0-next.27",

Any ideas would be great =)

**Comment by ThornWalli** [comment]
Hello @dissy123 ,

very strange, do you have `crossorigin="anonymous"` as attributes on the img tag of the poster?

**Example**
```html
<img class="image-7905b6c6 nuxt-speedkit-image" width="0" height="0" title="Youtube 1" alt="Youtube 1" loading="eager" decoding="async" crossorigin="anonymous">
```

**Comment by dissy123** [comment]
yes it is in the generated tag of the poster but not of the sources? 

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/5930734/754a2762-cf06-4524-945a-8f4dde60d8af)

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/5930734/fd62ea4d-06cf-4f8d-981e-7f1db39ac31e)

**Comment by ThornWalli** [comment]
I think I know what the problem is now 🙂

Did you define aliases and domains in the `@nuxt/image` settings?

```js
{
    image: {
      screens: {
        default: 320,
        xxs: 480,
        xs: 576,
        sm: 768,
        md: 996,
        lg: 1200,
        xl: 1367,
        xxl: 1600,
        '4k': 1921
      },
      domains: ['https://img.youtube.com', 'https://i.vimeocdn.com'],
      alias: {
        youtube: 'https://img.youtube.com',
        vimeo: 'https://i.vimeocdn.com'
      }
    }
}
```

**Comment by dissy123** [comment]
yes i'm setting those, but i work in a monorepo, i will have a look if they are really corectly set! :-) thanks for the hint

**Comment by dissy123** [comment]
okay they should be set, when i unset them then a false url is used 

<img width="711" alt="image" src="https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/5930734/3d2056bf-7c07-4aa6-9cca-2e1a100f7eaf">

**Comment by ThornWalli** [comment]
Does not seem to take effect from the settings. 
The images must be loaded via the IPX.

![image](https://github.com/GrabarzUndPartner/nuxt-speedkit/assets/8287751/ca8c13b8-ec04-455c-85ea-db265b16fe5d)

**I have two more attempts:**
1. Could you try with a `@nuxt/image` config object in the `nuxt-config`. `@nuxt/image` is automatically installed by the speedkit.  

```
    image: {
      // The screen sizes predefined by `@nuxt/image`:
      screens: {
        default: 320,
        xxs: 480,
        xs: 576,
        sm: 768,
        md: 996,
        lg: 1200,
        xl: 1367,
        xxl: 1600,
        '4k': 1921
      },
      domains: [
        'https://picsum.photos',
        'https://img.youtube.com',
        'https://i.vimeocdn.com',
        'https://i.pickadummy.com'
      ],
      alias: {
        picsum: 'https://picsum.photos',
        youtube: 'https://img.youtube.com',
        vimeo: 'https://i.vimeocdn.com',
        pickadummy: 'https://i.pickadummy.com'
      }
    },
```

2. or set `disableNuxtImage` to `false` in the speedkit settings if `@nuxt/image` itself is installed.

**Comment by dissy123** [comment]
Thank you it is now working! =)
I also had a other default provider setup in nuxt/image this and disabling the auto install of nuxt image worked like charme! =)

**Comment by ThornWalli** [comment]
Top! 🙂
